In [1]:
cd ..

/Users/wonjunekang/Desktop/MAS.S62/project/conversation-quality


In [3]:
import pandas as pd
import numpy as np
import os

In [20]:
csv_files = os.listdir('data/lvn/csv_preds_full_model')
csv_files

['lvn_452.csv',
 'lvn_453.csv',
 'lvn_451.csv',
 'lvn_450.csv',
 'lvn_454.csv',
 '.DS_Store']

In [23]:
for log_csv in sorted(csv_files):
    if log_csv.startswith('lvn'):
        csv_path = os.path.join('data/lvn/csv_preds_full_model', log_csv)
        xval_results_df = pd.read_csv(csv_path, delimiter='\t')
        print(log_csv)
        print(xval_results_df.mean().to_numpy().round(2))
        print(2*xval_results_df.std().to_numpy().round(2))
        print()


lvn_450.csv
[2.9  1.83 2.13 2.21]
[0.18 0.12 0.12 0.1 ]

lvn_451.csv
[2.93 1.8  2.15 2.21]
[0.38 0.24 0.22 0.16]

lvn_452.csv
[2.91 1.82 2.14 2.21]
[0.3  0.18 0.16 0.12]

lvn_453.csv
[2.92 1.82 2.13 2.21]
[0.24 0.14 0.14 0.12]

lvn_454.csv
[3.   1.8  2.18 2.22]
[0.62 0.28 0.32 0.24]

